SchoolHairAndMakeUP/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from core import views
from django.conf import settings

from django.views.static import serve



urlpatterns = [

    path('account/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('cart/', include('cart.urls')),
    path('coupons/', include('coupons.urls')),
    path('course/', include('courses.urls')),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit/', views.edit, name='edit'),
    path('form/', views.FormCoreView.as_view, name='main'),
    path('register/', views.register, name='register'),
    path('orders/', include('orders.urls')),
    path('shop/', include('shop.urls')),
    path('', views.main, name='main'),

]



if settings.DEBUG:
    urlpatterns += [
        re_path('^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

blog/urls.py
from django.urls import path, re_path
from django.contrib import auth
from django.urls import reverse_lazy
from blog import views

urlpatterns = [
    # templates views
    path('', views.PostListView.as_view(), name='post_list'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
]

cart/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_list_by_category',
                       args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    time = models.PositiveIntegerField(default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail',
                       args=[self.id, self.slug])


class ReviewStudio(models.Model):
    name = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    studio_review = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Отзыв от {}'.format(self.name.username)


class Masters(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='master/%Y/%m/%d', blank=True, default='teacher.jpg')
    body = models.TextField()
    position = models.CharField(max_length=50, default='position')
    direction = models.CharField(max_length=150, default='position')
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Мастера'
        verbose_name_plural = 'Мастера'

    @property
    def photo_url(self):
        if self.photo and hasattr(self.photo, 'url'):
            return self.photo.url

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

cart/forms.py
from django import forms

class CartAddProductForm(forms.Form):
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=1,
                 update_quantity=cd['update'])
    return redirect('cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request,
                  'cart/detail.html',
                  {'cart': cart,
                   'coupon_apply_form': coupon_apply_form})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% load staticfiles %}
{% block title %}
    Ваша корзина
{% endblock %}
{% block content %}

<div class="container-fluid body-back" style="padding-top:50px;padding-bottom:50px">
    <div class="container-fluid">
  <div class="row">
    <div class="col-sm">
    </div>

    <div class="col-8">
        <center><h3>Корзина покупок</h3></center>
        <hr>

  <center><table class="table_blur">
        <thead>
        <tr>
            <th colspan="2">Услуга</th>
            <th>Удалить</th>
            <th>Цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static 'core/img/no_image.jpg' %}
                                {% endif %}" class="mr-3" style="width: 5rem;">
                        </a>
                    </td>

                    <td><h6>{{ product.name }}</h6></td>
                    <td><a class="btn btn-outline-danger" href="{% url 'cart_remove' product.id%}">Удалить</a></td>
                    <td class="num">{{ item.price }} BYN</td>
                </tr>
            {% endwith %}
        {% endfor %}


        {% if cart.coupon %}
            <tr class="subtotal">
                <td>Цена до скидки</td>
                <td colspan="2"></td>
                <td class="num">{{ cart.get_total_price }} BYN</td>
            </tr>
            <tr>
                <td>
                    "{{ cart.coupon.code }}" купон
                    (скидка {{ cart.coupon.discount }} %)
                </td>
                <td colspan="2"></td>
                <td class="num neg">
                    - {{ cart.get_discount|floatformat:"2" }} BYN
                </td>
            </tr>
        {% endif %}
        <tr class="total">
            <td>Цена со скидкой</td>
            <td colspan="2"></td>
            <td class="num">
                {{ cart.get_total_price_after_discount|floatformat:"2" }} BYN
            </td>
        </tr>

        </tbody>

    </table></center>
        <hr>
        <center><form action="{% url 'apply' %}" method="post">
            <label >Скидочный купон:</label>
            {{ coupon_apply_form.code }}
            <button class="btn btn-outline-dark" type="submit" value="Apply">Применить</button>
            {% csrf_token %}
        </form></center>
        <hr>
    <center><h3>
        <div class="btn-group" role="group" aria-label="Basic example">
            <a href="{% url 'product_list' %}#shop-anchor"class="btn btn-outline-success">Продолжить покупки</a>
            {% if cart.get_total_price != 0%}
            <a href="{% url 'order_create' %}" class="btn btn-outline-info">
                Оформить заказ
            </a>
            {% endif %}
        </div>
    </h3></center>

    </div>


      <div class="col-sm">
        </div>
  </div>



</div>
</div>

{% endblock %}